### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [joshuatazrein/obsidian-time-ruler#16]
- recurring task option
- priority sort/ changing colors
- overdues sort 
- showing whole day in  timeline view, not just only hours ahead
- ability to drag tasks from notes or data view on timeline if its possible
- tag sort
- an easy way to remove tasks from timeline view ( in face remove time from tasks)
- draggable start and end point for tasks timeline view ( currently is not working well for me on pc)   
- if we have two  task source (tasks in different note)  in one block in  timeline like below, dragging one of them make system weirdly choose another to move.

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/82666844/52e778ef-7965-42e0-8292-d548615e5ad8)

**Comment by joshuatazrein** [comment]
Thanks for the issue! Here's what I think we'll do about these:

# Additions
- priority sort/ changing colors and tag sort: I will add the ability to filter tags and priority in the Search view. 
- recurring task option: This is in progress.
- an easy way to remove tasks from timeline view ( in face remove time from tasks): In the upcoming release you will be able to drag tasks to an "Unscheduled" button to remove them.
- if we have two task source (tasks in different note) in one block in timeline like below, dragging one of them make system weirdly choose another to move: I will see if I can reproduce this bug. Can you post the plaintext of these two files so I can try to replicate in a test vault?

# Already incorporated
- overdues sort: Due tasks show up in the Timeline view, so they are sorted that way. In the Search view they are organized by heading/file and sorting them there would break that structure.
- showing whole day in timeline view, not just only hours ahead: already incorporated, switch to Day view (the calendar button).
- draggable start and end point for tasks timeline view ( currently is not working well for me on pc): To drag a task's start point, you can drag the task itself. To drag its end point, you drag the bottom of the task itself (where the up and down arrow cursor shows). I could make the bottom end a little more intuitive.

# Longer term
- ability to drag tasks from notes or data view on timeline if its possible: This would be a long-term goal and I don't think it's really in-scope for the project. I am thinking of adding a right-click option on tasks to schedule them. You can also drag tasks from the Search view to anywhere to schedule them.

**Comment by joshuatazrein** [comment]
> * if we have two  task source (tasks in different note)  in one block in  timeline like below, dragging one of them make system weirdly choose another to move.
> 
> ![image](https://user-images.githubusercontent.com/82666844/257055389-52e778ef-7965-42e0-8292-d548615e5ad8.png)

This might be expected behavior:
- Dragging the horizontal line moves all tasks & headings
- Dragging a heading moves all tasks under that heading
- Dragging a single task moves that task and its children

Which one of these were you doing?

**Comment by joshuatazrein** [comment]
Update: the dragging headings error has been fixed in the upcoming release.

**Comment by joshuatazrein** [comment]
Update: right-click option to unschedule tasks and to schedule for now.

**Comment by PSEUDO-SAPPHO** [comment]
I appreciate your efforts. your recent updates were  great! Most of my issues have been resolved, and my experience has been excellent. However, I still have a few suggestions for improvement.
-In my app, changing the length of tasks in the calendar is not  still easy.
- Perhaps, in the long-term, having additional views such as a timeline could be beneficial, if its  in-scope for the project. Currently, the time-ruler is effective -for organizing small tasks, but there is room for improvement in terms of project management.- maybe  some customizable 
- The capability to sort tasks, even those that have been filtered using specific keywords, based on due dates or priority. This means having multiple sorting and filtering views. For instance, in amplenote, tasks can be viewed by individual notes they were created in, while still being sorted alphabetically or by priority.

**Comment by joshuatazrein** [comment]
Thanks for the suggestions:
- The upcoming release will have easier task dragging. Now you can just drag the length of the task. 
- Added red line showing current time
- Added more sorting options to "considering"
- There is currently no compatible way for recurring tasks. The Tasks plugin doesn't expose this API and I will need to implement it myself.
