### ISSUE TITLE
Parsing tasks without an emoji fails when date format is set to tasks emoji format

### ISSUE THREAD

**Issue by Osigmae** [joshuatazrein/obsidian-time-ruler#44]
**Describe the bug**
Parsing tasks without an emoji fails when date format is set to tasks emoji format. This results in time ruler not showing anything, since it threw an exception.

**To Reproduce**
Have a task with some text without an emoji or due, then start time ruler. Note, I am not completely sure this is what is causing the issue, but from the debugger, it looks like it fails to parse the date correctly.

- [ ] 18:00 setup a task example

**Expected behavior**
That time ruler would display things and not break and stop

**Screenshots**
![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/58618877/34adf4ee-e534-408b-b02e-ce120542b10b)

![image](https://github.com/joshuatazrein/obsidian-time-ruler/assets/58618877/7d2946c9-0c32-404b-96d0-f86458111179)

**Obsidian Version:** 
- [ ] Mobile
- [X] Desktop

**Additional context**

**Comment by brsma** [comment]
Same issue here

**Comment by joshuatazrein** [comment]
Ok, I think this is fixed in `1.3.2`, can you check?

**Comment by Osigmae** [comment]
@joshuatazrein I still get the same error, which triggers from the parseDateKey("completion"); function, which triggers from 'const tasks = newTasks.flatMap((item) => textToTask(item));'.

**Comment by Osigmae** [comment]
@joshuatazrein I've looked into it further in hopes I might help, and it happens inside the parseDateKey where it gets a task element which works fine. Then it asks this task element for a completion via 
item['completion'] which for the failing task returns "2023-03-16 17:42".

Then on this string it gets, it tries to call 'toIsoDate' which throws an uncaught exception, since toIsoDate doesn't exist. The void 0 will return undefined correctly on checking if the key value pair  'completion' -> "2023-03-16 17:42" exists, but there's no check for undefined for the toIsoDate function call, which throws the exception and halts the program. Maybe there's missing a library somewhere for string operations? I'm not a Javascript dev, so I don't know specifics, sorry.

**Comment by Osigmae** [comment]
@joshuatazrein I've looked a bit into how typescript works and the repo where ToIsoDate is used, and the problem might be that the particular TS code which generates that JS code does not assert what type it is working with to begin with. I take it this is a limitation of the typesystem in typescript, which results in the compiler not being able to validate the type error. Adding something like this to check the types to the TS code might solve it, sorry if it is not the correct syntax, but I hope the idea makes sense maybe? 

const parseDateKey = (key: 'due' | 'created' | 'start' | 'completion') => {
    let date;
    if (item[key] instanceof DateTime) {
        date = item[key].toISODate();
    } else {
        date = undefined;
    }
}

**Comment by joshuatazrein** [comment]
Thanks for looking into this. I've updated the code with your suggestion, and it will be uploaded in `1.3.3` later today.

```
const parseDateKey = (key: 'due' | 'created' | 'start' | 'completion') => {
    let date = item[key]
    if (item[key] instanceof DateTime) {
      date = item[key].toISODate() as string
    }
    if (!date) {
      // test tasks
      date = item.text.match(
        new RegExp(`${keyToTasksEmoji[key]} ?(${ISO_MATCH})`)
      )?.[1]
    }
    if (!date && key === 'due') {
      // test simple due
      date = titleLine.match(SIMPLE_DUE)?.[1]
    }
    if (!(typeof date === 'string')) return undefined
    return date
  }
```

**Comment by Osigmae** [comment]
Noice, tried with the updated build and it fixed the problem 👍
